"""Cross-cutting property-based invariant tests for the final semantic
hardening pass. These target invariants not already covered by a more
specific existing test file (test_calibration_regression.py,
test_llm_synthesis_boundary.py, test_causal_model.py, etc.) -- see those
files for the entity/temporal/provenance-specific regression coverage this
file deliberately does not duplicate.
"""

from __future__ import annotations

import pytest

from app.models.agent import (
    CandidateHypothesis,
    CapaAnalysis,
    CapaStatus,
    CanonicalFindingState,
    EvidenceItem,
    EvidenceStatus,
)


# ---------------------------------------------------------------------------
# PROPERTY 5: if no hypothesis survives, CAPA count must be zero.
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_zero_hypotheses_yields_zero_capa_actions():
    from app.agent.nodes.final_evidence_verification import final_evidence_verification_node
    finding = "The department is not following the required procedure correctly."
    mock_state = {
        "request": type("Request", (), {"finding_text": finding})(),
        "evidence_ledger": [
            EvidenceItem(claim="The department is not following the required procedure correctly.",
                         source="finding_text", status=EvidenceStatus.VERIFIED),
        ],
        "root_cause": type("RC", (), {
            "narrative": None, "statement": None, "status": "NOT_ESTABLISHED",
            "category": "TO_BE_CONFIRMED", "candidate_hypotheses": [],
        })(),
        "investigation_plan": type("Inv", (), {"questions": [], "areas": [], "evidence_to_collect": []})(),
        "capa_analysis": CapaAnalysis(status=CapaStatus.INVESTIGATION_REQUIRED, conditional_actions=[]),
        "ca_draft": None,
        "trace": [],
        "errors": [],
    }
    result = await final_evidence_verification_node(mock_state)
    assert result["root_cause"].candidate_hypotheses == []
    assert result["capa_analysis"].conditional_actions == []


@pytest.mark.asyncio
async def test_all_hypotheses_rejected_yields_zero_capa_actions():
    """Even when CAPA actions were PRE-POPULATED referencing hypothesis IDs
    that get rejected by the final firewall, the ID-consistency cleanup
    must strip them -- CAPA can never outlive the hypothesis it's
    conditional on."""
    from app.agent.nodes.final_evidence_verification import final_evidence_verification_node
    from app.models.agent import ConditionalCapaAction
    finding = "The required inspection was not completed."
    mock_state = {
        "request": type("Request", (), {"finding_text": finding})(),
        "evidence_ledger": [
            EvidenceItem(claim="The required inspection was not completed.", source="finding_text", status=EvidenceStatus.VERIFIED),
        ],
        "root_cause": type("RC", (), {
            "narrative": None, "statement": None, "status": "NOT_ESTABLISHED",
            "category": "TO_BE_CONFIRMED",
            "candidate_hypotheses": [
                CandidateHypothesis(id="H1", name="X", status="REFUTED", statement="A refuted hypothesis.", evidence_needed="x"),
            ],
        })(),
        "investigation_plan": type("Inv", (), {"questions": [], "areas": [], "evidence_to_collect": []})(),
        "capa_analysis": CapaAnalysis(
            status=CapaStatus.INVESTIGATION_REQUIRED,
            conditional_actions=[
                ConditionalCapaAction(if_cause_confirmed="IF H1 is confirmed", recommended_action="Do something."),
            ],
        ),
        "ca_draft": None,
        "trace": [],
        "errors": [],
    }
    result = await final_evidence_verification_node(mock_state)
    assert result["root_cause"].candidate_hypotheses == []
    assert result["capa_analysis"].conditional_actions == []


# ---------------------------------------------------------------------------
# PROPERTY 9: affected_object cannot be generated by more than one semantic
# producer -- verified by checking that _derive_deterministic_impact
# consumes canonical.finding_subject rather than recomputing it whenever
# canonical provides one, across several distinct subjects.
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("subject,finding_text", [
    ("balance BAL-014", "The balance BAL-014 was used after certificate expiry."),
    ("temperature log for refrigerator QC-REF-02", "The temperature log for refrigerator QC-REF-02 was incomplete."),
    ("daily equipment inspection checklist", "The daily equipment inspection checklist was not completed."),
])
def test_affected_object_always_traces_to_canonical_subject(subject, finding_text):
    from app.agent.nodes.core_synthesis import _derive_deterministic_impact
    canonical = CanonicalFindingState(
        raw_finding=finding_text, observed_deviation="x", finding_subject=subject,
    )
    impact, clean_noun, _, _ = _derive_deterministic_impact(finding_text, canonical, "x")
    assert clean_noun == subject
    assert impact.affected_object.lower() == subject.lower()


# ---------------------------------------------------------------------------
# PROPERTY 10: process_at_risk must not be reconstructed from
# affected_object's first noun alone.
# ---------------------------------------------------------------------------

def test_process_at_risk_not_derived_from_affected_object_first_noun():
    """"Balance BAL-014" as the entity must not produce a process name
    starting with "Balance" when the finding's own deviation names a
    different control domain (calibration)."""
    from app.agent.nodes.core_synthesis import _derive_deterministic_impact
    finding = (
        "During the audit, the calibration certificate for balance BAL-014 showed an "
        "expiry date of 10 August 2026. The balance was used for three production "
        "measurements on 12 August 2026."
    )
    canonical = CanonicalFindingState(raw_finding=finding, observed_deviation="x", finding_subject="balance BAL-014")
    impact, _, _, _ = _derive_deterministic_impact(finding, canonical, "x")
    assert not impact.process_at_risk.lower().startswith("balance")
    assert "calibration" in impact.process_at_risk.lower()


# ---------------------------------------------------------------------------
# PROPERTY 15: LLM provenance IDs must belong to the evidence ledger --
# already covered directly in test_llm_synthesis_boundary.py's Test 5/6;
# this adds the boundary case of a hypothesis mixing one valid and one
# invalid ID in the same list (not just all-invalid).
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_hypothesis_with_partially_invalid_provenance_is_rejected():
    import json
    from unittest.mock import AsyncMock, patch
    from app.agent.nodes.core_synthesis import core_synthesis_node
    from app.models.agent import InvestigateRequest

    finding = "The required inspection was not completed. The technician stated the gauge was broken."
    ledger = [
        EvidenceItem(claim="The required inspection was not completed.", source="finding_text", status=EvidenceStatus.VERIFIED),
        EvidenceItem(claim="The technician stated the gauge was broken.", source="finding_text", status=EvidenceStatus.REPORTED),
    ]
    state = {
        "request": InvestigateRequest(finding_text=finding),
        "evidence_ledger": ledger,
        "canonical_finding_state": CanonicalFindingState(raw_finding=finding, observed_deviation="x", finding_subject="inspection"),
        "investigation_plan": None, "trace": [], "errors": [],
    }
    bad_json = json.dumps({
        "root_cause": {
            "status": "NOT_ESTABLISHED", "category": "TO_BE_CONFIRMED", "statement": None,
            "candidate_hypotheses": [{
                "id": "H1", "name": "MIXED_PROVENANCE",
                "statement": "The gauge malfunction combined with an unrecorded event prevented inspection.",
                "status": "POSSIBLE",
                # C1 is real, C99 is not -- the whole hypothesis must be rejected,
                # not silently accepted because one of the two IDs is valid.
                "supporting_claim_ids": ["C1", "C99"], "contradicting_claim_ids": [],
                "evidence_needed": "record",
            }],
            "narrative": "x",
        },
        "five_why": {"steps": [], "is_complete": False, "status_note": "x"},
        "contributing_factors": [],
    })
    with patch("app.agent.nodes.core_synthesis.get_llm_client") as mock_get:
        mock_client = AsyncMock()
        mock_client.chat_completion.return_value = bad_json
        mock_get.return_value = mock_client
        result = await core_synthesis_node(state)
    assert "MIXED_PROVENANCE" not in [h.name for h in result["root_cause"].candidate_hypotheses]


# ---------------------------------------------------------------------------
# PROPERTY 4 / 8: MIXED requires an actual detected conflict, generalized
# beyond the calibration case already covered in test_calibration_regression.
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_mixed_five_why_status_requires_real_conflict_generic_case():
    from app.agent.nodes.final_evidence_verification import final_evidence_verification_node
    from app.models.agent import FiveWhyAnalysis, FiveWhyStep

    finding = "The required inspection was not completed for three consecutive days."
    mock_state = {
        "request": type("Request", (), {"finding_text": finding})(),
        "evidence_ledger": [
            EvidenceItem(claim="The required inspection was not completed for three consecutive days.",
                         source="finding_text", status=EvidenceStatus.VERIFIED),
        ],
        "canonical_finding_state": CanonicalFindingState(
            raw_finding=finding, observed_deviation="x", evidence_conflicts=[],
        ),
        "root_cause": type("RC", (), {
            "narrative": None, "statement": None, "status": "NOT_ESTABLISHED",
            "category": "TO_BE_CONFIRMED", "candidate_hypotheses": [],
        })(),
        "five_why": FiveWhyAnalysis(steps=[
            FiveWhyStep(
                question="Why was the inspection not completed?",
                answer="The inspection was not completed for three consecutive days.",
                status="MIXED",
            ),
        ]),
        "investigation_plan": type("Inv", (), {"questions": [], "areas": [], "evidence_to_collect": []})(),
        "capa_analysis": CapaAnalysis(status=CapaStatus.INVESTIGATION_REQUIRED, conditional_actions=[]),
        "ca_draft": None,
        "trace": [],
        "errors": [],
    }
    result = await final_evidence_verification_node(mock_state)
    assert result["five_why"].steps[0].status != "MIXED"


# ---------------------------------------------------------------------------
# PROPERTY 6: investigation questions may exist when hypothesis count is
# zero -- generalized to a second domain beyond calibration.
# ---------------------------------------------------------------------------

def test_zero_hypotheses_still_produces_investigation_questions_generic():
    from app.agent.nodes.plan_investigation_fallback import build_deterministic_investigation_plan
    finding = "The department is not following the required procedure correctly."
    ledger = [EvidenceItem(claim=finding, source="finding_text", status=EvidenceStatus.VERIFIED)]
    hyps, plan = build_deterministic_investigation_plan(finding, ledger)
    assert hyps == []
    assert len(plan.questions) >= 1


@pytest.mark.asyncio
async def test_checklist_revision_survives_hypothesis_demotion_with_questions_intact():
    """Live-discovered gap: the knowledge/revision-gap branch's ONE
    investigation question was bound to H1 via hypothesis_tested. When the
    causal-proposition eligibility layer correctly demotes H1 (no claim
    directly supports the hedged communication-gap mechanism), the
    ID-consistency firewall stripped that question too, leaving ZERO
    investigation content despite real unresolved uncertainty (Property 6).
    Neutral, non-hypothesis-bound questions must survive this demotion."""
    from app.agent.nodes.final_evidence_verification import final_evidence_verification_node
    from app.agent.nodes.plan_investigation_fallback import build_deterministic_investigation_plan

    finding = (
        "The daily equipment inspection checklist was not completed for three consecutive days. "
        "The operator stated that they were unaware that the checklist procedure had been revised."
    )
    ledger = [
        EvidenceItem(claim="The daily equipment inspection checklist was not completed for three consecutive days.",
                     source="finding_text", status=EvidenceStatus.VERIFIED),
        EvidenceItem(claim="The operator stated that they were unaware that the checklist procedure had been revised.",
                     source="finding_text", status=EvidenceStatus.REPORTED),
    ]
    hyps, plan = build_deterministic_investigation_plan(finding, ledger)
    assert len(plan.questions) >= 2
    assert any(q.hypothesis_tested is None for q in plan.questions)

    mock_state = {
        "request": type("Request", (), {"finding_text": finding})(),
        "evidence_ledger": ledger,
        "canonical_finding_state": CanonicalFindingState(
            raw_finding=finding, observed_deviation="checklist not completed",
            finding_subject="daily equipment inspection checklist",
        ),
        "root_cause": type("RC", (), {
            "narrative": None, "statement": None, "status": "NOT_ESTABLISHED",
            "category": "TO_BE_CONFIRMED", "candidate_hypotheses": hyps,
        })(),
        "investigation_plan": plan,
        "capa_analysis": CapaAnalysis(status=CapaStatus.INVESTIGATION_REQUIRED, conditional_actions=[]),
        "ca_draft": None,
        "trace": [],
        "errors": [],
    }
    result = await final_evidence_verification_node(mock_state)
    inv = result["investigation_plan"]
    assert inv.questions, "Investigation questions must survive even if H1 is demoted"
